apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: 
  creationTimestamp: null
  labels:
    app: authenticator
    version: 1.0.0
  name: authenticator
  selfLink: /api/v1/namespaces/services/authenticator
spec:
  selector:
    app: authenticator
    version: 1.0.0
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4242
  sessionAffinity: None
  type: LoadBalancer
